### PR TITLE
Shifting to Material You

### PR DESCRIPTION
**Pull request by PiyushSuthar**
I've redesigned (perhaps just reverted you may say) the UI around the material you UI and dynamic color based on the wallpaper and the preferred theme (light or dark mode). 

We still need to 
- redesign the Book page
- add a settings page with theme change and other options
- User account perhaps?? 
- add animations (I do have plans for it)

> I've tested it only on android

https://github.com/dstark5/Openlib/assets/32237558/affd546f-b60f-4e3b-9214-d7f811b551fe

### CODE REVIEW

**Comment by dstark5** [comment]
Hi, Thank for the contribution

This feature is not complete so please create a new branch and make a PR,So that I can accept.
Fdroid uses main to build .We requested fdroid to include our app if they accept they use the main branch.

**Comment by dstark5** [comment]
Hi,If you like to contribute we can create a discord server so we can discuss

**Comment by PiyushSuthar** [comment]
> Hi, Thank for the contribution
> 
> This feature is not complete so please create a new branch and make a PR,So that I can accept. Fdroid uses main to build .We requested fdroid to include our app if they accept they use the main branch.

Yeah sure.

**Comment by dstark5** [comment]
> > Hi, Thank for the contribution
> > This feature is not complete so please create a new branch and make a PR,So that I can accept. Fdroid uses main to build .We requested fdroid to include our app if they accept they use the main branch.
> 
> Make a new branch on the repo so that we can merge into that.

material-you branch has been created use that bro

**Pull request merged**
