### PR TITLE
View for non mobile platforms

### PR DESCRIPTION
**Pull request by bipinkrish**
Option to view PDF on Linux and Windows with system's default viewer (Temporary solution for viewing)
Database-Factory fix for Linux and Windows

### CODE REVIEW

**Comment by dstark5** [comment]
Reviewed the changes you made and approved the PR

**Comment by dstark5** [comment]
You can also help to build IOS release if you have a mac

**Comment by dstark5** [comment]
In main.dart
The following check should be added .Before It breaks the mobile app
`if (Platform.isWindows || Platform.isLinux || Platform.isMacOS) {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  }`

**Comment by bipinkrish** [comment]
ok i will make that changes

**Comment by bipinkrish** [comment]
Well for you other question, I don't have physical Mac but i can build it with GitHub Actions or other services but without apple developer account and signing the app it can't be installed on any devices

**Comment by dstark5** [comment]
> Well i didn't noticed it after checking it for Linux, sorry

Thats Okay

**Comment by dstark5** [comment]
> Well for your other question, I don't have physical Mac but i can build it with GitHub Actions or other services but without apple developer account and signing the app it can't be installed on any devices

Okay,While you develop for linux also check for android

**Pull request merged**
