### PR TITLE
Added book title and thumbnail sharing feature with image download and preview support

### PR DESCRIPTION
**Pull request by anshull-saxena**
Feature: Add functionality to share book title with thumbnail

- Download image from URL and save it to a temporary directory.
- Share the book title along with the thumbnail using `Share.shareXFiles`.
- Improved sharing experience by combining text and image in a single share intent.

### CODE REVIEW

**Comment by dstark5** [comment]
Hi @anshull-saxena 
Thanks for the work keep supporting 

Can you share a screenshot or video of how the share implemented as I wasn't currently able to test it so kindly share it I will merge it and also is the share button sharing the link for the book?

**Comment by anshull-saxena** [comment]
Hi @dstark5 
Implemented the share button! On both iOS and Android, it opens native share options with the direct link to the book.
Let me know if any changes are needed!

https://github.com/user-attachments/assets/644aef85-531d-4497-a43a-3110d5975c8c

android

**Comment by dstark5** [comment]
@anshull-saxena 
Awesome work man will merge the PR

Thank you 😊

**Comment by dstark5** [comment]
@anshull-saxena 
If you don't mind can pls add how did you setup the project locally to a readme setup.md file

**Comment by anshull-saxena** [comment]
Thanks for the feedback! I've added a setup guide to make it easier for others to set up the project locally. The guide is in the README.md file and covers installation, configuration, and running the app with Android Studio.

Let me know if there's anything else you'd like me to include! 😊

You can find the README file here: 
[README.md](https://github.com/user-attachments/files/17523444/README.md)

**Comment by dstark5** [comment]
Thanks @anshull-saxena 😊

**Pull request merged**
