### PR TITLE
Resumabale and background download

### PR DESCRIPTION
**Pull request by bipinkrish**

### CODE REVIEW

**Comment by dstark5** [comment]
Hey bro,Thanks for the contribution
The background download method you provided is a good,but we also need to consider

- For most books available in anna's archive has two mirrors
- The mirrors doesn't allow the user to concurrent downloads with same IP
- We need to implement the download with queue,One download at a time

Please check the above things in your code

**Comment by bipinkrish** [comment]
So i have to limit the download to one at a time, ok

**Comment by dstark5** [comment]
> So i have to limit the download to one at a time, ok

Okay,
when I Checking out your pull requests locally the download crash when I exit from the book info screen due to destroyed widget and the download stops, no working in pause and resume

**Comment by bipinkrish** [comment]
> the download crash when I exit from the book info screen due to destroyed widget and the download stops,

Yeah i see that, need to go with different approach

**Comment by dstark5** [comment]
> > the download crash when I exit from the book info screen due to destroyed widget and the download stops,
> 
> Yeah i see that, need to go with different approach

Hi,If you like to contribute we can create a discord server so we can discuss

**Comment by bipinkrish** [comment]
> > > the download crash when I exit from the book info screen due to destroyed widget and the download stops,
> > 
> > 
> > Yeah i see that, need to go with different approach
> 
> Hi,If you like to contribute we can create a discord server so we can discuss

Telegram or discord anything is fine for me

**Comment by dstark5** [comment]
> > > > the download crash when I exit from the book info screen due to destroyed widget and the download stops,
> > > 
> > > 
> > > Yeah i see that, need to go with different approach
> > 
> > 
> > Hi,If you like to contribute we can create a discord server so we can discuss
> 
> Telegram or discord anything is fine for me

Then I will update you once I created the the discord server

**Comment by dstark5** [comment]
Hi,If you like to contribute we can create a discord server so we can discuss

**Pull request closed without merging**
